-- ==========================================
-- SEED: 06 - POSTS - ARGENTINA (PROVINCIAS)
-- IDs: 8–16  |  location_ids: 8–16
-- ==========================================

INSERT INTO post (id, title, content, date, posted_at, is_by_ia, category, status, author_id, location_id) VALUES
(8,
 'Las Cataratas del Iguazú',
 'Descubiertas por Álvar Núñez Cabeza de Vaca en 1541, las Cataratas del Iguazú son una de las maravillas naturales más impresionantes del mundo. Con 275 saltos de agua, forman un espectáculo único en la frontera argentino-brasileña.',
 '1541-01-01', '2024-03-01', false, 'INFORMATION', 'ACTIVE', 2, 8),

(9,
 'El Glaciar Perito Moreno',
 'Nombrado en honor al explorador Francisco Moreno, este glaciar de 30 km de longitud es uno de los pocos que aún avanza. Su frente de 5 km de ancho y 60 metros de altura ofrece un espectáculo único cuando se desprenden bloques de hielo.',
 '1899-01-01', '2024-03-05', false, 'STORY', 'ACTIVE', 3, 9),

(10,
 'La Conquista del Aconcagua',
 'El 14 de enero de 1897, el suizo Matthias Zurbriggen alcanzó por primera vez la cumbre del Aconcagua, la montaña más alta de América con 6,962 metros. Esta hazaña marcó el inicio del montañismo en Argentina.',
 '1897-01-14', '2024-03-10', false, 'STORY', 'ACTIVE', 1, 10),

(11,
 'La Quebrada de Humahuaca',
 'Declarada Patrimonio de la Humanidad en 2003, la Quebrada de Humahuaca ha sido durante 10,000 años una ruta de intercambio cultural. Sus pueblos conservan tradiciones ancestrales y una arquitectura única.',
 '1500-01-01', '2024-03-15', false, 'INFORMATION', 'ACTIVE', 4, 11),

(12,
 'Península Valdés y las Ballenas',
 'Desde 1970, Península Valdés se convirtió en el santuario de ballenas más importante del mundo. Cada año, entre junio y diciembre, las ballenas francas australes llegan para reproducirse en estas aguas protegidas.',
 '1970-06-01', '2024-03-20', false, 'INFORMATION', 'ACTIVE', 2, 12),

(13,
 'La Cueva de las Manos',
 'Con más de 9,000 años de antigüedad, la Cueva de las Manos contiene las expresiones artísticas más antiguas de Sudamérica. Sus pinturas rupestres muestran manos en negativo y escenas de caza de guanacos.',
 '7000-01-01', '2024-03-25', false, 'STORY', 'ACTIVE', 4, 13),

(14,
 'Fundación de Salta',
 'El 16 de abril de 1582, Hernando de Lerma fundó la ciudad de Salta en el Valle de Lerma. Su arquitectura colonial y su ubicación estratégica la convirtieron en un importante centro comercial del noroeste argentino.',
 '1582-04-16', '2024-03-30', false, 'STORY', 'ACTIVE', 3, 14),

(15,
 'Bariloche y los Pioneros Alemanes',
 'A partir de 1895, inmigrantes alemanes se establecieron en la región de Bariloche, introduciendo la arquitectura alpina y la tradición chocolatera. Carlos Wiederhold fundó el primer hotel y estableció las bases del turismo patagónico.',
 '1895-01-01', '2024-04-01', false, 'STORY', 'ACTIVE', 1, 15),

(16,
 'Ushuaia: El Fin del Mundo',
 'Fundada en 1884 por Augusto Lasserre, Ushuaia se convirtió en la ciudad más austral del mundo. Su presidio, construido en 1902, albergó a los presos más peligrosos de Argentina hasta 1947.',
 '1884-10-12', '2024-04-05', false, 'INFORMATION', 'ACTIVE', 2, 16);

-- ==========================================
-- SEED: 06 - POSTS - ARGENTINA (PROVINCIAS) - NUEVAS ENTRADAS
-- IDs: 32–71
-- ==========================================

INSERT INTO post (id, title, content, date, posted_at, is_by_ia, category, status, author_id, location_id) VALUES
(32,
 'La Playa Bristol y el origen del turismo en Mar del Plata',
 'Mar del Plata fue fundada en 1874 y se convirtió en el primer destino turístico de Argentina cuando la aristocracia porteña comenzó a frecuentarla a fines del siglo XIX. La Playa Bristol, con su rambla y el icónico Hotel Provincial, fue el epicentro social de ese turismo de élite. A partir de la década de 1940, con el peronismo y las vacaciones pagas, se democratizó el acceso y se transformó en la ciudad balnearia más popular del país.',
 '1874-02-10', '2024-03-15', false, 'INFORMATION', 'ACTIVE', 1, 32),
(33,
 'La Piedra Movediza de Tandil y su misterioso derrumbe',
 'La Piedra Movediza de Tandil era una roca de aproximadamente 300 toneladas que se balanceaba sobre un cerro sin caer, convirtiéndose en símbolo de la ciudad desde la época colonial. El 29 de febrero de 1912 cayó de manera inesperada, generando gran consternación en la población y terminando con décadas de asombro popular. En 2007 se instaló una réplica exacta en fibra de vidrio para recuperar el emblema que había definido la identidad visual del municipio.',
 '1912-02-29', '2024-04-22', false, 'STORY', 'ACTIVE', 2, 33),
(34,
 'La Basílica de Luján y la leyenda de la Virgen patrona de Argentina',
 'La historia de Nuestra Señora de Luján comenzó en 1630 cuando una imagen de la Virgen fue trasladada en carreta desde Buenos Aires y, según la tradición, los bueyes se negaron a seguir avanzando en ese punto del camino, interpretado como señal divina. La basílica neogótica que hoy domina la ciudad fue construida entre 1887 y 1935, alcanzando una altura de 106 metros en sus torres. Luján es el principal santuario mariano de Argentina y recibe millones de peregrinos cada año, especialmente en la primera semana de octubre.',
 '1630-05-08', '2024-07-03', false, 'STORY', 'ACTIVE', 3, 34),
(35,
 'La Catedral de La Plata, la más grande de Argentina',
 'La Catedral de La Plata fue diseñada por el arquitecto Pedro Benoit e iniciada en 1884, apenas dos años después de la fundación de la ciudad, concebida como capital de la provincia de Buenos Aires. Su estilo neogótico tardó más de un siglo en completarse: las torres fueron inauguradas recién en 1999, convirtiéndola en una de las construcciones religiosas de mayor duración en América Latina. Con una capacidad para 14.000 personas y una nave central de 120 metros de largo, es la catedral más grande del país.',
 '1884-11-19', '2024-05-18', false, 'INFORMATION', 'ACTIVE', 4, 35),
(36,
 'La Manzana Jesuítica de Córdoba, Patrimonio de la Humanidad',
 'La Manzana Jesuítica de Córdoba fue declarada Patrimonio de la Humanidad por la UNESCO en el año 2000 junto con las estancias jesuíticas de la provincia. Fue construida a partir de 1613 cuando los jesuitas fundaron la Universidad Nacional de Córdoba, la más antigua del país, y el Colegio Máximo. El conjunto incluye la Iglesia de la Compañía de Jesús, cuya bóveda de madera tallada fue diseñada en 1671 tomando como modelo la quilla de un barco invertido.',
 '1613-06-01', '2024-02-09', false, 'INFORMATION', 'ACTIVE', 1, 36),
(37,
 'Villa Carlos Paz y el desarrollo turístico del lago San Roque',
 'El embalse San Roque fue inaugurado en 1891 como uno de los primeros diques de América del Sur y transformó radicalmente el paisaje serrano de Córdoba. Villa Carlos Paz creció como destino turístico en las primeras décadas del siglo XX, beneficiada por su cercanía al lago artificial y a las sierras chicas. Su famoso reloj cucú, instalado en 1958, se convirtió en un ícono de la ciudad y hoy es uno de los relojes de madera más grandes del mundo.',
 '1891-01-01', '2024-06-14', false, 'INFORMATION', 'ACTIVE', 2, 37),
(38,
 'La Cumbrecita, el pueblo alpino de las sierras cordobesas',
 'La Cumbrecita fue fundada en 1934 por inmigrantes alemanes y suizos que encontraron en las sierras grandes de Córdoba un paisaje similar al de los Alpes europeos. El pueblo fue declarado peatonal en 1982, siendo pionero en Argentina en preservar la circulación sin automóviles en su casco histórico. Su arquitectura de madera y piedra, junto con el río del Medio que atraviesa la localidad, le otorgan un aspecto inusual en el contexto sudamericano.',
 '1934-01-01', '2024-08-27', false, 'STORY', 'ACTIVE', 3, 38),
(39,
 'Las Estancias Jesuíticas de Jesús María, centro de la economía colonial',
 'La Estancia Jesuítica de Jesús María fue fundada en 1618 y constituye uno de los ejemplos mejor conservados de la arquitectura religiosa colonial en Argentina. Los jesuitas la utilizaron como base de producción agrícola y ganadera para financiar las actividades educativas en Córdoba, desarrollando técnicas avanzadas de irrigación. En sus bodegas se elaboró el primer vino documentado de Argentina, y hoy el sitio alberga el Museo Jesuítico Nacional declarado Patrimonio de la Humanidad.',
 '1618-01-01', '2024-09-05', false, 'INFORMATION', 'ACTIVE', 4, 39),
(40,
 'La Casa Histórica donde se declaró la Independencia Argentina',
 'El 9 de julio de 1816, en la Casa de Tucumán, el Congreso General Constituyente declaró la independencia de las Provincias Unidas en Sud América frente al dominio español, marcando el nacimiento formal de la nación argentina. El edificio original fue demolido en 1904 y reconstruido fielmente en 1943 a partir de planos y documentos históricos. Hoy funciona como museo nacional y conserva el salón donde se firmó el acta, considerado el lugar más sagrado de la historia cívica del país.',
 '1816-07-09', '2024-07-09', false, 'STORY', 'ACTIVE', 1, 40),
(41,
 'Tafí del Valle y los menhires de los pueblos originarios',
 'El Valle de Tafí fue habitado por la cultura Tafí hace más de 2.000 años, quienes erigieron menhires de piedra que superan los tres metros de altura con representaciones antropomorfas y zoomorfas aún no descifradas en su totalidad. En el Parque de los Menhires, situado en El Mollar, se reunieron decenas de estas piedras sagradas que habían sido dispersadas por los campos a lo largo de los siglos. El valle también fue refugio de religiosos jesuitas durante el período colonial y conserva una capilla del siglo XVIII de gran valor arquitectónico.',
 '0001-01-01', '2024-10-02', false, 'INFORMATION', 'ACTIVE', 2, 41),
(42,
 'El Carnaval de Gualeguaychú, el más largo del mundo',
 'El Carnaval de Gualeguaychú es reconocido como el carnaval más largo del mundo, extendiéndose durante todos los fines de semana de enero y febrero en el Corsódromo, un estadio al aire libre con capacidad para 35.000 personas. Sus comparsas, con carrozas de varios pisos y trajes cubiertos de plumas y lentejuelas, han ganado reconocimiento internacional desde la década de 1970. La ciudad entrerriana transformó esta festividad en su principal motor económico y cultural, atrayendo visitantes de toda América Latina.',
 '1949-01-01', '2024-01-20', false, 'INFORMATION', 'ACTIVE', 3, 42),
(43,
 'El Parque Nacional El Palmar y los yatay centenarios',
 'El Parque Nacional El Palmar fue creado en 1966 para proteger el último gran palmeral de yatay (Butia yatay) del mundo, una especie que en tiempos precoloniales cubría extensas áreas del litoral argentino y uruguayo. Las palmeras que sobreviven en el parque pueden superar los 800 años de edad y alcanzan hasta 12 metros de altura, constituyendo un ecosistema único. El río Uruguay bordea el parque y sus playas de arena fina complementan un paisaje singular que combina praderas, monte ribereño y palmar.',
 '1966-01-04', '2024-11-08', false, 'INFORMATION', 'ACTIVE', 4, 43),
(44,
 'Los Esteros del Iberá, el gran humedal de Corrientes',
 'Los Esteros del Iberá constituyen uno de los humedales más extensos del mundo, cubriendo aproximadamente 13.000 km² en la provincia de Corrientes con lagunas, bañados y esteros interconectados. El sistema alberga una biodiversidad extraordinaria con más de 650 especies de vertebrados, incluyendo el ciervo de los pantanos, el carpincho, el yacaré y el aguará guazú. En 2018 se relanzó el proyecto de reintroducción del yaguareté, que había sido extinguido en la región décadas atrás, con notable éxito reproductivo.',
 '1983-01-01', '2024-04-30', false, 'INFORMATION', 'ACTIVE', 1, 44),
(45,
 'La Costanera de Corrientes y la conexión con el río Paraná',
 'Corrientes fue fundada en 1588 por Juan de Torres de Vera y Aragón como avanzada estratégica sobre el río Paraná, en un punto donde el río se estrecha entre barrancas de arenisca roja. Su costanera es una de las más antiguas y pintorescas del litoral argentino, con edificios coloniales y modernistas conviviendo frente al ancho río. La ciudad es reconocida por su tradición del chamamé, ritmo musical declarado Patrimonio Cultural Inmaterial de la Humanidad por la UNESCO en 2020.',
 '1588-04-03', '2024-03-07', false, 'STORY', 'ACTIVE', 2, 45),
(46,
 'El Monumento a la Bandera en Rosario, donde nació la enseña nacional',
 'El 27 de febrero de 1812, Manuel Belgrano izó por primera vez la Bandera Argentina en Rosario, en las baterías Libertad e Independencia que custodiaban el Paraná. El Monumento Nacional a la Bandera, inaugurado en 1957 tras 20 años de construcción, se erige en ese sitio histórico sobre el río y es considerado el mayor monumento nacional de Argentina. Rosario, fundada como aldea en 1689, fue la ciudad que paradójicamente careció de acta de fundación formal pero albergó el nacimiento del símbolo patrio más emblemático.',
 '1812-02-27', '2024-02-27', false, 'STORY', 'ACTIVE', 3, 46),
(47,
 'El Convento San Francisco de Santa Fe, el más antiguo del país',
 'El Convento de San Francisco en Santa Fe es considerado el edificio más antiguo en uso de Argentina, con partes de su construcción que datan del siglo XVII. Fue fundado por los franciscanos en 1680 en el sitio donde Juan de Garay había establecido la ciudad en 1573, trasladada desde su emplazamiento original en Santa Fe la Vieja. Sus paredes de adobe, vigas de timbó y una pinacoteca colonial con obras del siglo XVIII lo convierten en un documento vivo de la historia colonial rioplatense.',
 '1680-01-01', '2024-06-21', false, 'INFORMATION', 'ACTIVE', 4, 47),
(48,
 'La Plaza Independencia de Mendoza, reconstruida tras el terremoto',
 'El 20 de marzo de 1861 un devastador terremoto destruyó casi por completo la ciudad de Mendoza, causando entre 6.000 y 12.000 muertos sobre una población de 18.000 habitantes. La nueva ciudad fue planificada por el ingeniero francés Julio Balloffet con amplias plazas y anchos bulevares, diseño pensado para resistir futuros sismos y facilitar la evacuación. La Plaza Independencia, corazón del damero reconstruido, concentra el Teatro Municipal, el Museo de Arte Moderno subterráneo y es escenario de la Vendimia, fiesta de la cosecha vitivinícola.',
 '1861-03-20', '2024-03-20', false, 'STORY', 'ACTIVE', 1, 48),
(49,
 'El Valle de Uco y la vitivinicultura de altura en Mendoza',
 'El Valle de Uco se extiende al pie de la Cordillera de los Andes a una altitud de entre 900 y 1.500 metros sobre el nivel del mar, condiciones que producen vinos de alta gama reconocidos internacionalmente. La irrigación con agua de deshielo del volcán Tupungato permitió el desarrollo vitícola desde el período colonial, aunque la modernización con variedades como el Malbec se consolidó a fines del siglo XX. Hoy el valle concentra más de 60 bodegas boutique y es considerado uno de los territorios vitivinícolas más prometedores del hemisferio sur.',
 '1556-01-01', '2024-09-14', false, 'INFORMATION', 'ACTIVE', 2, 49),
(50,
 'La Confluencia de Neuquén, origen de una ciudad estratégica',
 'La ciudad de Neuquén fue fundada en 1904 en la confluencia de los ríos Limay y Neuquén, que juntos forman el río Negro, en un punto estratégico para el control de la Patagonia norte. El ferrocarril llegó ese mismo año y la ciudad creció aceleradamente como centro comercial y administrativo de la región. El descubrimiento de petróleo en la cuenca neuquina en 1918 transformó la economía provincial y convirtió a Neuquén en una de las ciudades de mayor crecimiento de Argentina durante el siglo XX.',
 '1904-12-12', '2024-05-25', false, 'INFORMATION', 'ACTIVE', 3, 50),
(51,
 'El Volcán Lanín, guardián sagrado de los mapuches',
 'El volcán Lanín, con sus 3.776 metros de altura, es un estratovolcán de forma cónica casi perfecta que domina el paisaje de la frontera entre Argentina y Chile en la Patagonia. Para los mapuches es una montaña sagrada conocida como el "padre de los volcanes" y constituye un sitio de peregrinación espiritual desde tiempos inmemoriales. El Parque Nacional Lanín, creado en 1937, protege el volcán y los extensos bosques de araucarias o pehuenes, árbol sagrado del pueblo mapuche que puede vivir más de 1.000 años.',
 '1937-05-11', '2024-10-19', false, 'INFORMATION', 'ACTIVE', 4, 51),
(52,
 'Villa La Angostura y el Bosque de Arrayanes único en el mundo',
 'Villa La Angostura alberga en la Península Quetrihué el único bosque puro de arrayanes del mundo, un árbol de tronco canela y hojas perennes que en condiciones únicas de humedad y suelo patagónico forma masas forestales exclusivas. Los arrayanes del parque tienen entre 300 y 650 años de edad y sus troncos retorcidos de color canela crean paisajes de cuento. Se dice que Walt Disney visitó el bosque en la década de 1940 y se inspiró en él para diseñar el bosque de Bambi, aunque esta anécdota no ha sido verificada documentalmente.',
 '0001-01-01', '2024-07-31', false, 'STORY', 'ACTIVE', 1, 52),
(53,
 'Ischigualasto, el Valle de la Luna y el origen de los dinosaurios',
 'El Parque Provincial Ischigualasto en San Juan preserva la formación geológica más completa del período Triásico del mundo, con rocas de entre 230 y 210 millones de años que contienen fósiles de los dinosaurios más antiguos conocidos, como el Eoraptor y el Herrerasaurus. Las erosiones del viento y la lluvia sobre arcillas y tobas volcánicas crearon paisajes selenitas de gran belleza, con formaciones como la Cancha de Bochas y el Gusano. En 2000 fue declarado Patrimonio de la Humanidad junto con el Parque Nacional Talampaya, formando un corredor paleontológico sin igual.',
 '0001-01-01', '2024-08-12', false, 'INFORMATION', 'ACTIVE', 2, 53),
(54,
 'La Difunta Correa, devoción popular en el desierto sanjuanino',
 'Deolinda Correa fue una mujer que, según la tradición popular, murió de sed en el desierto de San Juan en la década de 1840 siguiendo a su esposo soldado durante las guerras civiles, pero su hijo recién nacido fue encontrado vivo amamantando del pecho de su cadáver. Desde entonces el santuario en Vallecito se convirtió en uno de los centros de devoción popular más importantes de América Latina, con millones de devotos que llevan botellas de agua como ofrenda. Aunque no reconocida por la Iglesia Católica, la Difunta Correa es un ejemplo paradigmático de la religiosidad popular argentina.',
 '1840-01-01', '2024-04-05', false, 'STORY', 'ACTIVE', 3, 54),
(55,
 'El Parque Nacional Talampaya y sus cañones de roca roja',
 'El Parque Nacional Talampaya en La Rioja fue declarado Patrimonio de la Humanidad por la UNESCO en el año 2000 y protege uno de los yacimientos paleontológicos y arqueológicos más importantes del país. Sus cañones de arenisca roja alcanzan hasta 150 metros de altura y conservan petroglifos y pictografías de culturas prehispánicas como la Ciénaga y la Aguada que habitaron la zona hace más de 2.000 años. El nombre Talampaya proviene del quechua y del kakán y significa "río del tala seco" en referencia al árbol autóctono.',
 '1997-12-11', '2024-11-22', false, 'INFORMATION', 'ACTIVE', 4, 55),
(56,
 'Chilecito y el Cable Carril más alto del mundo en su época',
 'Chilecito fue fundada en 1715 en el fértil valle del Famatina, en La Rioja, y cobró gran importancia a principios del siglo XX gracias a la explotación de las minas de oro y plata del Cerro Famatina. Entre 1903 y 1907 se construyó el Cable Carril de La Mejicana, una obra de ingeniería con 35 km de longitud y estaciones a más de 4.600 metros de altura, considerado el más alto del mundo en su momento. Hoy el primer tramo del cable puede recorrerse como atracción turística y la ciudad es también conocida por su producción de aceitunas y nueces.',
 '1715-01-01', '2024-06-03', false, 'INFORMATION', 'ACTIVE', 1, 56),
(57,
 'Antofagasta de la Sierra y la Puna catamarqueña milenaria',
 'Antofagasta de la Sierra es uno de los poblados de mayor altitud habitada de Argentina, ubicado a 3.350 metros sobre el nivel del mar en la Puna de Catamarca, rodeado de volcanes, salares y lagunas de flamencos. La región fue habitada por las culturas Alamito y Aguada hace más de 2.000 años, dejando vestigios en conchales y sitios de procesamiento de camélidos que aún se estudian. El paisaje lunar, los cielos despejados y la pervivencia de tradiciones precolombinas en la cría de llamas y la artesanía en lana hacen del lugar un destino de interés antropológico único.',
 '0001-01-01', '2024-05-08', false, 'INFORMATION', 'ACTIVE', 2, 57),
(58,
 'San Ignacio Miní, las ruinas jesuíticas más visitadas de Argentina',
 'San Ignacio Miní fue fundada por los jesuitas en 1632 como una de las misiones del sistema de reducciones guaraníes que llegó a reunir a más de 100.000 indígenas en el nordeste de Sudamérica. Las ruinas conservan la planta completa de la ciudad misional con su iglesia, claustro, talleres y celdas, construidas en piedra rojiza con decoración barroca guaraní única. Tras la expulsión de los jesuitas en 1767, las misiones fueron abandonadas y la selva fue cubriendo los edificios hasta que las excavaciones del siglo XX las devolvieron a la luz; fueron declaradas Patrimonio de la Humanidad en 1984.',
 '1632-01-01', '2024-07-20', false, 'INFORMATION', 'ACTIVE', 3, 58),
(59,
 'Resistencia, la ciudad de las esculturas del Chaco',
 'Resistencia, capital del Chaco, es conocida como "la ciudad de las esculturas" por contar con más de 800 obras de arte en sus espacios públicos, la mayor concentración de escultura urbana de América Latina. Esta tradición comenzó en 1988 con la creación del Fogón de los Arrieros y la Bienal Internacional de Escultura, que convoca artistas de todo el mundo a trabajar y donar sus obras a la ciudad. La región chaqueña fue de las últimas en ser sometida militarmente en Argentina, con el territorio indígena qom finalmente ocupado a fines del siglo XIX.',
 '1878-02-02', '2024-09-28', false, 'INFORMATION', 'ACTIVE', 4, 59),
(60,
 'El Bañado La Estrella, el humedal formoseño del Pilcomayo',
 'El Bañado La Estrella es un humedal de origen fluvial ubicado en el centro-oeste de Formosa, formado por el desborde estacional del río Pilcomayo que inunda una planicie de más de 400.000 hectáreas creando un mosaico de lagunas, esteros y pajonales. Este ecosistema es hogar del yaguareté, el tapir, el pecarí y cientos de especies de aves acuáticas, constituyendo uno de los últimos refugios de fauna del Gran Chaco sudamericano. Los pueblos originarios pilagá y wichí han habitado esta región durante milenios, desarrollando una profunda relación cultural y de subsistencia con el humedal.',
 '0001-01-01', '2024-10-15', false, 'INFORMATION', 'ACTIVE', 1, 60),
(61,
 'Las Termas de Río Hondo y la historia termal del norte argentino',
 'Las Termas de Río Hondo en Santiago del Estero son conocidas desde la época precolombina: los pueblos tonocoté y lule utilizaban sus aguas calientes con propiedades medicinales antes de la llegada española. El balneario moderno se desarrolló a partir de la década de 1930, cuando la llegada del ferrocarril permitió el acceso masivo de turistas en busca de curas reumáticas y dermatológicas. Con más de 200 hoteles con piletas termales propias, la ciudad recibe anualmente alrededor de un millón de visitantes y es el destino termal más importante de Argentina.',
 '1533-01-01', '2024-02-14', false, 'INFORMATION', 'ACTIVE', 2, 61),
(62,
 'Purmamarca y el Cerro de los Siete Colores, maravilla geológica',
 'El Cerro de los Siete Colores que domina el pueblo de Purmamarca en Jujuy exhibe una paleta de tonos que incluye el rojo, amarillo, violeta, verde, blanco y gris, producto de la superposición de distintas formaciones geológicas de entre 200 y 600 millones de años. El pueblo de Purmamarca data del siglo XVII y mantiene una arquitectura colonial de adobe armoniosa con el paisaje quebradense que lo rodea. La Quebrada de Humahuaca, en la que se integra Purmamarca, fue declarada Patrimonio de la Humanidad por la UNESCO en 2003 por su valor cultural y paisajístico.',
 '1648-01-01', '2024-01-27', false, 'INFORMATION', 'ACTIVE', 3, 62),
(63,
 'El Bolsón y su tradición de comunidades alternativas en la Patagonia',
 'El Bolsón, ubicado en un valle cordillerano de Río Negro a 300 metros sobre el nivel del mar, tiene un microclima inusual para la Patagonia que permite el cultivo de lúpulo, frutas finas y hortalizas, actividades que le dieron una economía singular. En los años 1970 fue destino de una corriente migratoria de jóvenes en busca de modos de vida alternativos, lo que dejó una impronta cultural hippie y artesanal que persiste hasta hoy en su feria regional. La ciudad fue declarada municipio no nuclear en 1984, siendo una de las primeras localidades de América Latina en adoptar esa postura.',
 '1889-01-01', '2024-08-03', false, 'STORY', 'ACTIVE', 4, 63),
(64,
 'El Parque Provincial Luro y la historia del ciervo colorado en La Pampa',
 'El Parque Provincial Luro en La Pampa fue la estancia de caza del político y terrateniente Pedro Olegario Luro, quien a comienzos del siglo XX introdujo el ciervo colorado europeo, el jabalí y otras especies exóticas en un coto privado de 7.600 hectáreas. Tras convertirse en área protegida provincial en 1965, el parque enfrenta hoy el desafío de manejar la población de ciervos que impacta sobre la vegetación nativa del caldenal pampeano. El castillo de estilo normando construido por Luro en 1906 y su bosque de palmeras washingtonias son vestigios materiales de la opulencia de la oligarquía terrateniente argentina.',
 '1906-01-01', '2024-11-05', false, 'STORY', 'ACTIVE', 1, 64),
(65,
 'Merlo, el microclima serrano de San Luis y sus propiedades curativas',
 'Merlo en San Luis está ubicada al pie de las sierras de los Comechingones a 920 metros de altitud y posee un microclima excepcional reconocido científicamente por su alta ionización negativa del aire y bajos niveles de humedad, características que atraen a personas con afecciones respiratorias y reumáticas. La región fue habitada por los pueblos comechingón y ranquel antes de la colonización española, que fundaron el pueblo en 1797 como posta en el camino hacia Cuyo. El turismo de bienestar y naturaleza se consolidó desde la década de 1980, convirtiendo a Merlo en uno de los destinos serranos más valorados del centro argentino.',
 '1797-01-01', '2024-04-11', false, 'INFORMATION', 'ACTIVE', 2, 65),
(66,
 'Esquel y el Tren Patagónico La Trochita, reliquia del siglo XX',
 'Esquel en Chubut es punto de partida del famoso tren de trocha angosta conocido como "La Trochita" o Old Patagonian Express, que recorre 402 km hasta Ingeniero Jacobacci con locomotoras a vapor del año 1922 que aún están en funcionamiento. El ferrocarril fue inaugurado en 1945 y sirvió durante décadas como único medio de comunicación y transporte de carga entre los poblados patagónicos. Paul Theroux lo inmortalizó en su libro "El Viejo Expreso de la Patagonia" (1979), transformándolo en un símbolo de la resistencia de la era del vapor frente a la modernización del transporte.',
 '1945-05-25', '2024-07-15', false, 'STORY', 'ACTIVE', 3, 66),
(67,
 'El Lago del Desierto y la disputa territorial con Chile',
 'El Lago del Desierto en Santa Cruz fue escenario del último conflicto territorial armado entre Argentina y Chile en 1965, cuando una escaramuza entre gendarmería argentina y carabineros chilenos resultó en la muerte del teniente argentino Ernesto Esquivel Moreno. La disputa por la soberanía del área fue sometida a arbitraje internacional y resuelta recién en 1994 a favor de Argentina, siendo uno de los últimos diferendos limítrofes resueltos entre los dos países. El lago, ubicado en los confines del Campo de Hielo Sur, es accesible solo en temporada estival y ofrece uno de los paisajes más remotos y vírgenes de la Patagonia austral.',
 '1965-11-06', '2024-12-01', false, 'STORY', 'ACTIVE', 4, 67),
(68,
 'Sierra de la Ventana y el Parque Tornquist, serranías bonaerenses',
 'El Parque Provincial Ernesto Tornquist en el sudoeste de Buenos Aires protege el sistema serrano de Ventana, el más elevado de la provincia con el Cerro Tres Picos a 1.239 metros, y conserva pastizales naturales con guanacos y ñandúes. La región fue habitada por pueblos cazadores-recolectores durante miles de años antes de la llegada de los tehuelches, quienes usaban las cuevas serranas como refugio y dejaron pinturas rupestres en el Abra de la Ventana. El parque fue donado al Estado en 1937 por la familia Tornquist, estanciero alemán que había colonizado la zona a fines del siglo XIX.',
 '1937-01-01', '2024-09-22', false, 'INFORMATION', 'ACTIVE', 1, 68),
(69,
 'Miramar, la ciudad del niño y sus médanos costeros',
 'Miramar fue fundada en 1888 a 45 km al sur de Mar del Plata y se desarrolló como balneario familiar con playas de arenas finas, médanos y la reserva forestal más antigua de la Argentina, plantada artificialmente en 1914 para frenar el avance de los médanos sobre la ciudad. El Vivero Florentino Ameghino, con más de 500 hectáreas de pinos, eucaliptos y acacias plantados hace más de un siglo, constituye un pulmón verde inusual en la costa atlántica bonaerense. La ciudad fue apodada "la ciudad del niño" en la década de 1960 por sus propuestas de turismo familiar.',
 '1888-01-01', '2024-01-12', false, 'INFORMATION', 'ACTIVE', 2, 69),
(70,
 'Colón y las termas del Litoral en Entre Ríos',
 'Colón fue fundada en 1863 sobre el río Uruguay y sus termas de agua salada con propiedades terapéuticas fueron descubiertas durante exploraciones petroleras en la década de 1980, a más de 1.000 metros de profundidad, con temperaturas de hasta 45 grados. La ciudad es también puerta de acceso al Parque Nacional El Palmar y está unida a la uruguaya Paysandú por un puente internacional sobre el río Uruguay inaugurado en 1975.',
 '1863-06-01', '2024-03-29', false, 'INFORMATION', 'ACTIVE', 3, 70),
(71,
 'Paraná y el Túnel Subfluvial, obra de ingeniería que unió dos provincias',
 'El Túnel Subfluvial Raúl Uranga-Carlos Sylvestre Begnis, inaugurado en 1969, fue la primera obra de ingeniería subacuática de América Latina, uniendo las ciudades de Paraná y Santa Fe bajo el río Paraná con un túnel de 2,4 km de extensión. Paraná, fundada en 1730 como puerto estratégico sobre la barranca del Paraná, fue capital de la Confederación Argentina entre 1853 y 1861 durante la separación con Buenos Aires. Su costanera, que domina el ancho río desde la barranca alta, es uno de los paseos más característicos del litoral argentino.',
 '1969-12-20', '2024-02-22', false, 'STORY', 'ACTIVE', 4, 71);

-- ── Islas Malvinas ────────────────────────────────────────────────────────
INSERT INTO post (id, title, content, date, posted_at, is_by_ia, category, status, author_id, location_id) VALUES
(172,
 'Las Islas Malvinas: Un territorio argentino usurpado por Gran Bretaña',
 'Las Islas Malvinas fueron descubiertas por navegantes españoles en el siglo XVI y administradas por el Virreinato del Río de la Plata como parte del Imperio Español. Al independizarse Argentina en 1816, heredó la soberanía sobre el archipiélago por el principio del uti possidetis juris: las nuevas naciones recibían los mismos territorios que correspondían a las divisiones coloniales españolas. El gobierno de Buenos Aires ejerció su soberanía activamente: nombró gobernadores, reguló la pesca y la caza de lobos marinos, y estableció una colonia permanente. El 3 de enero de 1833, una fragata de guerra británica expulsó por la fuerza al gobernador argentino Luis Vernet y a sus colonos, imponiendo una ocupación que Argentina nunca reconoció como legítima. Desde entonces, Argentina ha reclamado sistemáticamente la soberanía ante todos los foros internacionales: la Asamblea General de las Naciones Unidas aprobó la Resolución 2065 en 1965, la 3160 en 1973 y la 37/9 en 1982, llamando a ambos países a negociar la soberanía. Gran Bretaña, sin embargo, se ha negado sistemáticamente a negociar mientras la situación no cambie sobre el terreno. La causa Malvinas es una cuestión de Estado para todos los gobiernos argentinos, considerada la herida colonial abierta más emblemática de América Latina.',
 '1833-01-03', '2024-04-02', false, 'STORY', 'ACTIVE', 1, 172);

INSERT INTO post (id, title, content, date, posted_at, is_by_ia, category, status, author_id, location_id) VALUES
(173,
 'La Guerra de Malvinas de 1982: La reconquista que no pudo ser',
 'El 2 de abril de 1982, tropas argentinas desembarcaron en Puerto Stanley y recuperaron militarmente las Islas Malvinas, poniendo fin a 149 años de ocupación británica. La operación fue ordenada por la dictadura militar del general Leopoldo Galtieri, que buscaba recuperar popularidad interna en un contexto de crisis económica y creciente oposición civil. La respuesta del gobierno de Margaret Thatcher fue inmediata: movilizó una flota de guerra de más de 100 buques que recorrió 13.000 kilómetros para llegar al Atlántico Sur. El 2 de mayo, el crucero argentino ARA General Belgrano fue torpedeado por un submarino nuclear británico mientras navegaba fuera de la zona de exclusión declarada por Gran Bretaña, con un saldo de 323 muertos: fue la mayor pérdida de vidas de la guerra para Argentina y uno de los episodios más controvertidos del conflicto. Soldados argentinos, en su mayoría conscriptos de 18 y 19 años mal equipados, enfrentaron a profesionales británicos en combates en Monte Longdon, Wireless Ridge y Darwin. El 14 de junio de 1982, tras 74 días de conflicto, Argentina firmó la rendición. Murieron 649 argentinos, 255 británicos y 3 civiles isleños. La derrota aceleró el fin de la dictadura y la recuperación de la democracia en Argentina.',
 '1982-04-02', '2024-06-14', false, 'STORY', 'ACTIVE', 3, 172);

INSERT INTO post (id, title, content, date, posted_at, is_by_ia, category, status, author_id, location_id) VALUES
(174,
 'El Cementerio de Darwin: Los soldados que volvieron a casa',
 'En el Cementerio de Darwin, sobre las colinas ventosas de las Islas Malvinas, descansan los restos de 237 soldados argentinos que murieron en el conflicto de 1982. Durante décadas, 123 de esas tumbas llevaron la inscripción "Soldado argentino solo conocido por Dios", porque las familias nunca supieron dónde estaban sus hijos. El Comité Internacional de la Cruz Roja, junto con el Equipo Argentino de Antropología Forense, inició en 2017 un proceso de identificación mediante análisis de ADN. Para 2023, más de 115 soldados habían sido identificados, devolviendo a sus familias décadas después la certeza de dónde descansaban sus muertos. Los conscriptos que lucharon en Malvinas, muchos de ellos de 18 años, enfrentaron a su regreso el silencio de un país que prefería olvidar: la derrota fue tabú durante años, y los veteranos denunciaron durante décadas el abandono estatal. Algunos fueron víctimas de la propia dictadura que los mandó a combatir. La tasa de suicidios entre veteranos de Malvinas superó ampliamente al número de caídos en combate, una estadística que expone la dimensión real del trauma no tratado. El cementerio de Darwin es hoy un lugar de peregrinación para las familias argentinas que, por primera vez, pueden llevar flores a una tumba con nombre.',
 '1982-06-14', '2024-04-02', false, 'STORY', 'ACTIVE', 1, 173);

-- ── Mitos y leyendas argentinos ───────────────────────────────────────────
INSERT INTO post (id, title, content, date, posted_at, is_by_ia, category, status, author_id, location_id) VALUES
(175,
 'La Pachamama: La Madre Tierra que todo lo da y todo lo pide',
 'La Pachamama es la deidad femenina más importante de los pueblos andinos: la Madre Tierra que concede fertilidad a los campos, salud al ganado y prosperidad a las comunidades. Su culto, anterior al Imperio Inca, se extiende por Argentina, Bolivia, Perú, Chile y Ecuador, y sobrevivió a la conquista española integrándose en formas sincréticas con el catolicismo. Cada año, el 1 de agosto, las comunidades del noroeste argentino realizan la Corpachada: cavan un pozo en la tierra o abren una "boca" en el suelo y ofrecen a la Pachamama coca, chicha, alimentos, cigarrillos y otros objetos queridos, pidiendo permiso y agradeciéndole por sus dones. La tierra devora las ofrendas como señal de que han sido aceptadas. Durante todo agosto, se cree que la Pachamama está hambrienta y lista para cobrar lo que se le adeuda: los que no hacen la ofrenda pueden sufrir enfermedades, accidentes o malas cosechas. En los últimos años, el culto a la Pachamama se extendió a las ciudades argentinas y a sectores del ambientalismo global, que ven en ella un símbolo de la relación respetuosa entre los seres humanos y la naturaleza. La Constitución del Estado Plurinacional de Bolivia de 2009 reconoció a la Pachamama como sujeto de derechos.',
 '0001-01-01', '2024-08-01', false, 'MYTH', 'ACTIVE', 3, 62);

INSERT INTO post (id, title, content, date, posted_at, is_by_ia, category, status, author_id, location_id) VALUES
(176,
 'El Gauchito Gil: El santo milagroso de los caminos argentinos',
 'Antonio Mamerto Gil Núñez, conocido como el Gauchito Gil, es el santo popular más venerado de Argentina. Nació alrededor de 1840 en Mercedes, Corrientes, y según la leyenda era un gaucho que robaba a los estancieros ricos para dar a los pobres, convirtiéndose en una figura de resistencia contra la injusticia. Desertor del ejército para no matar a sus hermanos en las guerras civiles, fue capturado y ejecutado el 8 de enero de 1878: lo colgaron de los pies en un árbol de espinillo a las afueras de Mercedes y le cortaron el cuello. Antes de morir, el Gauchito profetizó que quien rogara por su alma salvaría la vida de su hijo. Según la tradición, el soldado que lo ejecutó llegó a su casa esa noche para encontrar a su hijo gravemente enfermo, rezó al Gauchito, y el niño se recuperó milagrosamente. La noticia se propagó por el litoral y el culto creció de forma espontánea, completamente al margen de la Iglesia Católica. Hoy, millones de conductores argentinos adornan sus vehículos con banderines y estatuillas rojas del Gauchito Gil. En la ruta nacional 123, frente al lugar de su muerte, se levanta un santuario que recibe cientos de miles de peregrinos cada 8 de enero. Es el culto popular de mayor crecimiento en Argentina desde el siglo XX.',
 '1878-01-08', '2024-01-08', false, 'MYTH', 'ACTIVE', 1, 174);

INSERT INTO post (id, title, content, date, posted_at, is_by_ia, category, status, author_id, location_id) VALUES
(177,
 'El Nahuelito: El monstruo del lago patagónico que nadie pudo atrapar',
 'El Lago Nahuel Huapi, en la Patagonia argentina, esconde según la leyenda a un enorme animal desconocido apodado el Nahuelito: la versión sudamericana del monstruo del Lago Ness. La palabra "nahuel" significa jaguar o tigre en mapudungun, y la tradición mapuche habla desde tiempos inmemoriales de un ser poderoso que vive en las profundidades del lago y puede adoptar distintas formas. El primer avistamiento registrado por un extranjero data de 1910, cuando el ganadero norteamericano George Garret afirmó haber visto una criatura de más de cuatro metros de largo y cuello alargado emergiendo de las aguas. En 1922, el oceanógrafo Clemente Onelli lanzó una expedición oficial en busca del animal, que atrajo la atención de la prensa internacional y terminó sin resultados concretos. A lo largo del siglo XX, docenas de testigos reportaron haber visto formas oscuras moviéndose bajo la superficie, fotografías borrosas circularon por los medios, y la criatura se convirtió en atracción turística regional. Las hipótesis científicas incluyen la posibilidad de que se trate de un plesiosauro sobreviviente, una nutria gigante o simplemente grandes ejemplares de peces endémicos del lago. El Nahuelito sigue siendo uno de los misterios más queridos de la Patagonia argentina.',
 '0001-01-01', '2024-11-15', false, 'MYTH', 'ACTIVE', 2, 175);

INSERT INTO post (id, title, content, date, posted_at, is_by_ia, category, status, author_id, location_id) VALUES
(178,
 'El Pombero: El espíritu del monte que castiga a los descuidados',
 'El Pombero, también llamado Pombéro o Kurupi en distintas tradiciones guaraníes, es uno de los seres mitológicos más temidos del litoral argentino y paraguayo. Se lo describe como un hombre pequeño, oscuro, cubierto de pelo, con pies al revés y sombrero de paja que siempre lleva puesto: su rasgo más inquietante es que puede hacerse invisible y moverse sin hacer ruido, lo que lo convierte en un espía del monte. Según las comunidades de Corrientes, Entre Ríos y Misiones, el Pombero es el guardián de la naturaleza: protege a los animales y los pájaros del cazador desconsiderado. Silbar al mediodía o en la oscuridad de la noche es invocarlo, y quien lo molesta puede perder la voz, enloquecer o desaparecer en el monte para siempre. Sin embargo, si alguien le deja ofrendas de tabaco, miel o caña (bebida alcohólica), el Pombero puede convertirse en un aliado y proteger el hogar. En muchos pueblos del litoral, los padres usan la amenaza del Pombero para que los niños no se alejen del rancho al caer la tarde. Con la migración rural a las ciudades, el mito viajó junto a las familias y hoy se lo invoca igual en las periferias urbanas de Corrientes y Posadas.',
 '0001-01-01', '2024-05-20', false, 'MYTH', 'ACTIVE', 2, 44);
